package pl.hamsterdev.pott

object Consts {
    const val EXPIRE_NOTIFICATION_ITEM_NAME_PARAM = "itemName"
    const val EXPIRE_NOTIFICATION_ITEM_QUANTITY_PARAM = "itemQuantity"
    const val EXPIRE_NOTIFICATION_ITEM_DAYS_LEFT_PARAM = "itemDaysLeft"

    const val EXPIRE_NOTIFICATION_WORKER_DAYS_BEFORE_EXPIRE = -8
    const val EXPIRE_NOTIFICATION_WORKER_HOUR_OF_DAY = 10
    const val EXPIRE_NOTIFICATION_WORKER_MINUTES = 0
    const val EXPIRE_NOTIFICATION_WORKER_SECOND = 0
}